<div id="direct-download" class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <strong><?php qe(_('Popular apps')); ?></strong>
                <a
                    aria-hidden="true"
                    class="glyphicon glyphicon-question-sign notranslate"
                    href="<?php qe(url('help')); ?>#popular-apps-box"
                    target="_blank"
                ></a>
            </div>
            <div class="panel-body">
                <ul id="direct-download-list" class="list-unstyled">
                    <?php foreach(unserialize(DIRECT_DOWNLOADS) as $label => $package): ?>
                        <li
                            class="col-xs-3 app-list-item"
                        ><a class="download" href="<?php qe(url("download/direct/$package")); ?>">
                            <?php qe($label); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
