<script type="application/x-social-share-privacy-settings">
{
    path_prefix: "<?php qe(BASE_URL); ?>ext-libs/jquery.socialshareprivacy/",
    css_path:    "css/jquery.socialshareprivacy.min.css",
    services: {
        flattr: {status: false},
        buffer: {status: false},
        delicious: {status: false},
        disqus: {status: false},
        fbshare: {status: false},
        hackernews: {status: false},
        linkedin: {status: false},
        pinterest: {status: false},
        reddit: {status: false},
        stumbleupon: {status: false},
        tumblr: {status: false},
        xing: {status: false},
        mail: {status: false}
    },
    order: ['facebook', 'gplus', 'twitter', 'flattr'],
    info_link: '<?php qe(url("privacy")); ?>#social-media',
}
</script>